//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoIDCode.WSMatricula {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.ObligacionPago cd_gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Padre cd_padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((this.cd_alumnoField.Equals(value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.ObligacionPago cd_grado {
            get {
                return this.cd_gradoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_gradoField, value) != true)) {
                    this.cd_gradoField = value;
                    this.RaisePropertyChanged("cd_grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Padre cd_padre {
            get {
                return this.cd_padreField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_padreField, value) != true)) {
                    this.cd_padreField = value;
                    this.RaisePropertyChanged("cd_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_apellido {
            get {
                return this.ds_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_apellidoField, value) != true)) {
                    this.ds_apellidoField = value;
                    this.RaisePropertyChanged("ds_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_nombre {
            get {
                return this.ds_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_nombreField, value) != true)) {
                    this.ds_nombreField = value;
                    this.RaisePropertyChanged("ds_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObligacionPago", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class ObligacionPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_gradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal qt_montoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_grado {
            get {
                return this.cd_gradoField;
            }
            set {
                if ((this.cd_gradoField.Equals(value) != true)) {
                    this.cd_gradoField = value;
                    this.RaisePropertyChanged("cd_grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_grado {
            get {
                return this.ds_gradoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_gradoField, value) != true)) {
                    this.ds_gradoField = value;
                    this.RaisePropertyChanged("ds_grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal qt_monto {
            get {
                return this.qt_montoField;
            }
            set {
                if ((this.qt_montoField.Equals(value) != true)) {
                    this.qt_montoField = value;
                    this.RaisePropertyChanged("qt_monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Padre", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Padre : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_padreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_apellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_nombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_padre {
            get {
                return this.cd_padreField;
            }
            set {
                if ((this.cd_padreField.Equals(value) != true)) {
                    this.cd_padreField = value;
                    this.RaisePropertyChanged("cd_padre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_apellido {
            get {
                return this.ds_apellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_apellidoField, value) != true)) {
                    this.ds_apellidoField = value;
                    this.RaisePropertyChanged("ds_apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_nombre {
            get {
                return this.ds_nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_nombreField, value) != true)) {
                    this.ds_nombreField = value;
                    this.RaisePropertyChanged("ds_nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Nota", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Nota : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Alumno cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_notaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string desc_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int qt_notaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Alumno cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_nota {
            get {
                return this.cd_notaField;
            }
            set {
                if ((this.cd_notaField.Equals(value) != true)) {
                    this.cd_notaField = value;
                    this.RaisePropertyChanged("cd_nota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string desc_curso {
            get {
                return this.desc_cursoField;
            }
            set {
                if ((object.ReferenceEquals(this.desc_cursoField, value) != true)) {
                    this.desc_cursoField = value;
                    this.RaisePropertyChanged("desc_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int qt_nota {
            get {
                return this.qt_notaField;
            }
            set {
                if ((this.qt_notaField.Equals(value) != true)) {
                    this.qt_notaField = value;
                    this.RaisePropertyChanged("qt_nota");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LibroPendiente", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class LibroPendiente : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Alumno cd_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Libro cd_libroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_pendienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dt_fecha_devolucionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dt_fecha_prestamoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Alumno cd_alumno {
            get {
                return this.cd_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_alumnoField, value) != true)) {
                    this.cd_alumnoField = value;
                    this.RaisePropertyChanged("cd_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Libro cd_libro {
            get {
                return this.cd_libroField;
            }
            set {
                if ((object.ReferenceEquals(this.cd_libroField, value) != true)) {
                    this.cd_libroField = value;
                    this.RaisePropertyChanged("cd_libro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_pendiente {
            get {
                return this.cd_pendienteField;
            }
            set {
                if ((this.cd_pendienteField.Equals(value) != true)) {
                    this.cd_pendienteField = value;
                    this.RaisePropertyChanged("cd_pendiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_fecha_devolucion {
            get {
                return this.dt_fecha_devolucionField;
            }
            set {
                if ((this.dt_fecha_devolucionField.Equals(value) != true)) {
                    this.dt_fecha_devolucionField = value;
                    this.RaisePropertyChanged("dt_fecha_devolucion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_fecha_prestamo {
            get {
                return this.dt_fecha_prestamoField;
            }
            set {
                if ((this.dt_fecha_prestamoField.Equals(value) != true)) {
                    this.dt_fecha_prestamoField = value;
                    this.RaisePropertyChanged("dt_fecha_prestamo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cd_libroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_autorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_tituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cd_libro {
            get {
                return this.cd_libroField;
            }
            set {
                if ((this.cd_libroField.Equals(value) != true)) {
                    this.cd_libroField = value;
                    this.RaisePropertyChanged("cd_libro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_autor {
            get {
                return this.ds_autorField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_autorField, value) != true)) {
                    this.ds_autorField = value;
                    this.RaisePropertyChanged("ds_autor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_titulo {
            get {
                return this.ds_tituloField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_tituloField, value) != true)) {
                    this.ds_tituloField = value;
                    this.RaisePropertyChanged("ds_titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Alumno aluField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cod_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_estadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ds_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dt_fechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal qt_montoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Alumno alu {
            get {
                return this.aluField;
            }
            set {
                if ((object.ReferenceEquals(this.aluField, value) != true)) {
                    this.aluField = value;
                    this.RaisePropertyChanged("alu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cod_pago {
            get {
                return this.cod_pagoField;
            }
            set {
                if ((this.cod_pagoField.Equals(value) != true)) {
                    this.cod_pagoField = value;
                    this.RaisePropertyChanged("cod_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_estado {
            get {
                return this.ds_estadoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_estadoField, value) != true)) {
                    this.ds_estadoField = value;
                    this.RaisePropertyChanged("ds_estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ds_pago {
            get {
                return this.ds_pagoField;
            }
            set {
                if ((object.ReferenceEquals(this.ds_pagoField, value) != true)) {
                    this.ds_pagoField = value;
                    this.RaisePropertyChanged("ds_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dt_fecha {
            get {
                return this.dt_fechaField;
            }
            set {
                if ((this.dt_fechaField.Equals(value) != true)) {
                    this.dt_fechaField = value;
                    this.RaisePropertyChanged("dt_fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal qt_monto {
            get {
                return this.qt_montoField;
            }
            set {
                if ((this.qt_montoField.Equals(value) != true)) {
                    this.qt_montoField = value;
                    this.RaisePropertyChanged("qt_monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReservaMatricula", Namespace="http://schemas.datacontract.org/2004/07/WcfService.Dominio")]
    [System.SerializableAttribute()]
    public partial class ReservaMatricula : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ProyectoIDCode.WSMatricula.Alumno AlumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private char EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaReservaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ProyectoIDCode.WSMatricula.Alumno Alumno {
            get {
                return this.AlumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.AlumnoField, value) != true)) {
                    this.AlumnoField = value;
                    this.RaisePropertyChanged("Alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((this.CodigoField.Equals(value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public char Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaReserva {
            get {
                return this.FechaReservaField;
            }
            set {
                if ((this.FechaReservaField.Equals(value) != true)) {
                    this.FechaReservaField = value;
                    this.RaisePropertyChanged("FechaReserva");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSMatricula.IReservaService")]
    public interface IReservaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarAlumno", ReplyAction="http://tempuri.org/IReservaService/ConsultarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno ConsultarAlumno(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarAlumno", ReplyAction="http://tempuri.org/IReservaService/ConsultarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> ConsultarAlumnoAsync(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarPadre", ReplyAction="http://tempuri.org/IReservaService/ConsultarPadreResponse")]
        ProyectoIDCode.WSMatricula.Padre ConsultarPadre(int cd_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ConsultarPadre", ReplyAction="http://tempuri.org/IReservaService/ConsultarPadreResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Padre> ConsultarPadreAsync(int cd_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarAlumno", ReplyAction="http://tempuri.org/IReservaService/registarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno registarAlumno(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarAlumno", ReplyAction="http://tempuri.org/IReservaService/registarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> registarAlumnoAsync(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Alumno[] ListarAlumno(int id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno[]> ListarAlumnoAsync(int id_padre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarNotaAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarNotaAlumnoResponse")]
        ProyectoIDCode.WSMatricula.Nota[] ListarNotaAlumno(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarNotaAlumno", ReplyAction="http://tempuri.org/IReservaService/ListarNotaAlumnoResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Nota[]> ListarNotaAlumnoAsync(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/IReservaService/ListarLibrosPrestadosResponse")]
        ProyectoIDCode.WSMatricula.LibroPendiente[] ListarLibrosPrestados(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarLibrosPrestados", ReplyAction="http://tempuri.org/IReservaService/ListarLibrosPrestadosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.LibroPendiente[]> ListarLibrosPrestadosAsync(int codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarPagos", ReplyAction="http://tempuri.org/IReservaService/ListarPagosResponse")]
        ProyectoIDCode.WSMatricula.Pago[] ListarPagos(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/ListarPagos", ReplyAction="http://tempuri.org/IReservaService/ListarPagosResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Pago[]> ListarPagosAsync(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarReserva", ReplyAction="http://tempuri.org/IReservaService/registarReservaResponse")]
        ProyectoIDCode.WSMatricula.ReservaMatricula registarReserva(int cd_alumno);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReservaService/registarReserva", ReplyAction="http://tempuri.org/IReservaService/registarReservaResponse")]
        System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.ReservaMatricula> registarReservaAsync(int cd_alumno);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReservaServiceChannel : ProyectoIDCode.WSMatricula.IReservaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReservaServiceClient : System.ServiceModel.ClientBase<ProyectoIDCode.WSMatricula.IReservaService>, ProyectoIDCode.WSMatricula.IReservaService {
        
        public ReservaServiceClient() {
        }
        
        public ReservaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReservaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProyectoIDCode.WSMatricula.Alumno ConsultarAlumno(int cd_alumno) {
            return base.Channel.ConsultarAlumno(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> ConsultarAlumnoAsync(int cd_alumno) {
            return base.Channel.ConsultarAlumnoAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.Padre ConsultarPadre(int cd_padre) {
            return base.Channel.ConsultarPadre(cd_padre);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Padre> ConsultarPadreAsync(int cd_padre) {
            return base.Channel.ConsultarPadreAsync(cd_padre);
        }
        
        public ProyectoIDCode.WSMatricula.Alumno registarAlumno(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido) {
            return base.Channel.registarAlumno(cd_padre, ds_nombre, cd_grado, ds_apellido);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno> registarAlumnoAsync(int cd_padre, string ds_nombre, int cd_grado, string ds_apellido) {
            return base.Channel.registarAlumnoAsync(cd_padre, ds_nombre, cd_grado, ds_apellido);
        }
        
        public ProyectoIDCode.WSMatricula.Alumno[] ListarAlumno(int id_padre) {
            return base.Channel.ListarAlumno(id_padre);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Alumno[]> ListarAlumnoAsync(int id_padre) {
            return base.Channel.ListarAlumnoAsync(id_padre);
        }
        
        public ProyectoIDCode.WSMatricula.Nota[] ListarNotaAlumno(int cd_alumno) {
            return base.Channel.ListarNotaAlumno(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Nota[]> ListarNotaAlumnoAsync(int cd_alumno) {
            return base.Channel.ListarNotaAlumnoAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.LibroPendiente[] ListarLibrosPrestados(int codigo) {
            return base.Channel.ListarLibrosPrestados(codigo);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.LibroPendiente[]> ListarLibrosPrestadosAsync(int codigo) {
            return base.Channel.ListarLibrosPrestadosAsync(codigo);
        }
        
        public ProyectoIDCode.WSMatricula.Pago[] ListarPagos(int cd_alumno) {
            return base.Channel.ListarPagos(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.Pago[]> ListarPagosAsync(int cd_alumno) {
            return base.Channel.ListarPagosAsync(cd_alumno);
        }
        
        public ProyectoIDCode.WSMatricula.ReservaMatricula registarReserva(int cd_alumno) {
            return base.Channel.registarReserva(cd_alumno);
        }
        
        public System.Threading.Tasks.Task<ProyectoIDCode.WSMatricula.ReservaMatricula> registarReservaAsync(int cd_alumno) {
            return base.Channel.registarReservaAsync(cd_alumno);
        }
    }
}
